language: java
sudo: false
services:
  - docker
before_install:
- docker build -t manojrpms/check:1.5.${TRAVIS_BUILD_NUMBER}.${TRAVIS_JOB_NUMBER}-bronze .
- docker login --username manojrpms  --password manoj@ilimi1
- docker push manojrpms/check:1.5.${TRAVIS_BUILD_NUMBER}.${TRAVIS_JOB_NUMBER}-bronze


