language: java
sudo: false
services:
 - docker

install:
 - docker build -t manojrpms/check:1.5.0-$TRAVIS_BUILD_NUMBER-bronze .
script:
 - docker login --username manojrpms  --password $hub_pass
 - docker push manojrpms/check:1.5.0-$TRAVIS_BUILD_NUMBER-bronze
env:
  global:
     - secure: "GESug2CeYXPUCKjADayDJeIlxIl9Qr+S6oVDWKuvqOvgwBqv5j2jL6BBpFW+jLRlI6gr3XXCK/c9q9sXnjgcRkK0AJ2wDp3tpv/4b/lglD6LD425Ui5dSav+qoHxOagrxRcjQM075OZLlWNCDXI0ST6ggBLabnbEYWq7bNl7O7sW4oLT3PA6DHGuhURs7A6Cbp0lNQFQ45vBy9BeOOSGorU6ZB9T5TPthjeUfE0DRL+tvd0RsUxKJwugVk+JTIq6WZvco6FHNqoKXekTKGVqNnb+/vcai6BdnyTx+se44oxCaEzKiRGjvPUXSBkliAbX8tMrW8S5fS1u7Ia/NsVy5qo4UfQHEgJa9tHJ5PhT1CXhkqiWpObw71NHl7fW7IdxuLWzZ31HHwofBsurRiRDCB0XkwdKi6Px7GuzbrGRqFQN8NVHc3jSiXA4GZH3z7GCZycwFWod+PFm06VedooeX5usXQsGhuhMytu66Q2lNrf8kglr4xMN8QT0AV80qimLekN53o+BIZLSxNgafBwChtQcSZPrms/tnmnMweXEvHpo9Z+MszIYDoDvw7uIWoPw/LpuLxxGJsfyHZVGCMEzqEKCgp6ld8Bzoodfktyzct3wdVNy/JbfUx91b94QP0Nm4NfJbLNm27xs+XImJg96gy2Tz+LVLB9ddqLZqPAREs4="
